
version: '3.7'
services:
    db_postgres:
        container_name: 'db_boilerplate'
        image: postgres:14
        restart: always
        env_file:
          - .env
        ports:
          - '5433:5433'
        volumes:
          - pgdata:/var/lib/postgresql/data
    volumes: 
     pgdata: